### ISSUE TITLE
Empty list?

### ISSUE THREAD

**Issue by Rapid1898-code** [batuhanaky/mailscout#1]
Hello - i tried your module using the following code:

```
from mailscout import Scout
scout = Scout()
names = [["Jeff", "Winger"], ["Ben Cheng"], ["Łukas Nowicki"]]
domain = "microsoft.com"
emails = scout.find_valid_emails(domain, names)
print(emails)
```

But i only get back an empty list:

```
(test) C:\DEV\Python-Diverses\mailscout>python try.py
[]
```

**Comment by batuhanaky** [comment]
Hey, I copied the snippet and ran it on Google Colab. Had no problem. Seems like it's a local problem with your environment. Let me try to identify it. 

MailScout can't work when port 25 is blocked. Are you running this code on a VPS or a cloud instance? They sometimes block port 25 by default.

If you run it locally on your computer, it may also be about your network configuration. If you use a school network or such environment, they also block port 25 by default. If that's the scenario and you have no control over the network, you may try running it on Colab or a similar service.

**Comment by Rapid1898-code** [comment]
Hello - no vps or cloud instance - just a normal computer.
no school network or such environment

**Comment by batuhanaky** [comment]
I tried to replicate your problem but couldn't face any issues using 3 residential networks during the day. The issue is caused by port 25, maybe your modem settings or ISP themselves are blocking it. I can only advise you should use a different network.

If you can't solve the port problem, you can use Google Colab for free to use MailScout without the hassle.
